apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  type: NodePort
  selector:
    app: weather-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008  # You can omit this to auto-assign
