apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api-postgres-deployment
  labels:
    app: weather-api-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api-postgres
  template:
    metadata:
      labels:
        app: weather-api-postgres
    spec:
      containers:
      - name: weather-api-postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_DB
          value: "Weather"
        envFrom:
          - secretRef:
              name: postgres-secret
        volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

