apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # Use ClusterIP for internal communication within the cluster.
  type: ClusterIP
  selector:
    app: weather-api-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432