services:
  postgres:
    image: postgres:17
    container_name: weather_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass#4o&6
      POSTGRES_DB: Weather
    networks:
      - weather  
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  weather:
    external: true
